export const STOP_LOADER = 'STOP_LOADER';
export const START_LOADER = 'START_LOADER';
export const TELEMETRY_DATA_FETCHED = 'TELEMETRY_DATA_FETCHED';
export const TELEMETRY_DATA_FETCHED_ERROR = 'TELEMETRY_DATA_FETCHED_ERROR';
